### ISSUE TITLE
Nonce cannot be verified

### ISSUE THREAD

**Issue by mfru** [svandragt/htmxpress#4]
I was having trouble with `hx-post` to `/htmx/demo/partial-ascii` and it turns out that the nonce in `$_SERVER` is actually called `HTTP_X_WP_NONCE` and not `X_WP_NONCE`.

After fixing it locally, I was getting the right response instead of getting the `security nope`. (uncommented for debugging)

I am uncertain if this is an issue with my (very vanilla) setup or a bug.

Also, very cool idea to integrate htmx with WordPress. This feels like it could be very productive!

**Comment by svandragt** [comment]
Thanks for your report and contributing to the project @mfru I've fixed the nonce verification it now matches the REST-API nonce verification.
